const constants = {
    FETCH_GIFS: "FETCH_GIFS",
    CHANGE_GIFS: "CHANGE_GIFS",
    CLEAR_GIFS: "CLEAR_GIFS",
    
    CLEAR_SEARCH_FIELD: "CLEAR_SEARCH_FIELD",
    SET_SEARCH_FIELD: "SET_SEARCH_FIELD"
}

export default constants